name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up build environment
      run: |
        apt-get update
        apt-get install -y \
            git \
            zip \
            unzip \
            python3-pip \
            openjdk-17-jdk \
            zlib1g-dev \
            libncurses5-dev \
            libgdbm-dev \
            libnss3-dev \
            libssl-dev \
            libsqlite3-dev \
            libreadline-dev \
            libffi-dev \
            libbz2-dev

    - name: Install Buildozer
      run: |
        pip3 install --upgrade pip
        pip3 install buildozer cython==0.29.36 virtualenv
        buildozer init

    - name: Build APK
      run: |
        buildozer -v android debug
        mkdir artifacts
        cp bin/*.apk artifacts/

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: aimhigh-apk
        path: artifacts/*.apk
        retention-days: 5
