name: Full-Feature APK Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Increased timeout
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libtinfo5 cmake libffi-dev \
          libssl-dev libbluetooth-dev libnfc-dev

    - name: Install Buildozer with full features
      run: |
        pip install buildozer cython
        pip install kivy[full]

    - name: Build APK (Full Features)
      run: |
        buildozer -v android clean
        buildozer -v android debug deploy
        
        # Include all shared libraries
        mkdir -p libs/arm64-v8a
        cp -r /home/runner/.buildozer/android/platform/build-armeabi-v7a/dists/aichat__arm64-v8a/libs/arm64-v8a/*.so libs/arm64-v8a/
        
        # Package extra assets
        zip -r bin/full_features.zip libs/ resources/

    - name: Upload APK with Extras
      uses: actions/upload-artifact@v3
      with:
        name: full-feature-apk
        path: |
          bin/*.apk
          bin/full_features.zip
