Name: Full-Feature APK Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    uses: actions/checkout@v4

    name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    name: Install system dependencies
      Run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libtinfo5 cmake libffi-dev \
          libssl-dev libbluetooth-dev libnfc-dev

    name: Install Buildozer with full features
      Run: |
        Pip install - upgrade pip wheel
        Pip install buildozer cython
        Pip install kivy[full]

    name: Build APK
      Run: |
        buildozer -v android clean
        buildozer -v android debug
        
        # Verify APK exists
        ls -lh bin/
        
        # Package additional files (if needed)
        mkdir -p libs/arm64-v8a
        [ -d "/home/runner/.buildozer/android/platform/build-armeabi-v7a/dists/aichat__arm64-v8a/libs/arm64-v8a/" ] && \
          cp -r /home/runner/.buildozer/android/platform/build-armeabi-v7a/dists/aichat__arm64-v8a/libs/arm64-v8a/*.So libs/arm64-v8a/ || true
        
        [ -d "resources" ] & zip -r bin/full_features.zip libs/ resources/ || true

    name: Create Release
      if: success()
      uses: softprops/action-gh-release@v1
      with:
        Files: |
          bin/*.apk
          bin/full_features.zip
        tag_name: v1.0.0
        generate_release_notes: true
      name: Cache buildozer dependencies 
     uses: actions/cache@v3
     with:
    path: |
      ~/.buildozer
      ~/.gradle
    Key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
